name: Build Binary and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release
        uses: softprops/action-gh-release@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract meta from Git Ref
        id: extract_meta
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/tags\/v//')
          else
            VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "commit_date=$(git show -s --format=%cI)" >> "$GITHUB_OUTPUT"


      - name: Release Go Binary
        uses: wangyoucao577/go-release-action@v1
        with:
          pre_command: export CGO_ENABLED=0
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ldflags: >-
            -s -w
            -X "github.com/krau/remdit/config.Version=${{ env.VERSION }}"
            -X "github.com/krau/remdit/config.BuildTime=${{ steps.extract_meta.outputs.commit_date }}"
            -X "github.com/krau/remdit/config.Commit=${{ github.sha }}"
            -X "github.com/krau/remdit/config.defaultServer=${{ secrets.REMDIT_DEFAULT_SERVER }}"
          binary_name: remdit
        env:
          VERSION: ${{ env.VERSION }}
